"""Export recorded actions to an on-device Android shell script.

自动精灵手机版 stores each recording as a script you can run *on the phone*.
Here a recording (a list of `Action`) is compiled to a `.sh` that drives the
device with Android's built-in `input` command — no PC, no ADB needed at replay
time: `sh recording.sh` inside Termux or `adb shell sh /sdcard/recording.sh`.

The compiler is a pure function (Actions in, script text out) so it is fully
unit-testable. Timing between actions is preserved with `sleep`, mirroring
`recorder.Player`'s relative-timing replay.
"""
from __future__ import annotations

from typing import Iterable

from .actions import Action, load_actions

SHEBANG = "#!/system/bin/sh"


def _q(s: str) -> str:
    """Single-quote a string for POSIX sh (safe against shell metacharacters)."""
    return "'" + str(s).replace("'", "'\\''") + "'"


def _sleep_line(seconds: float) -> str:
    # Android's toybox/busybox `sleep` accepts fractional seconds.
    return f"sleep {seconds:.3f}".rstrip("0").rstrip(".")


def action_to_cmd(a: Action) -> str:
    """Translate one Action into a single Android `input` command line.

    `wait` produces a `sleep`; every other kind maps to `input ...`.
    """
    p = a.params
    if a.kind == "tap":
        return f"input tap {int(p['x'])} {int(p['y'])}"
    if a.kind == "long_press":
        x, y = int(p["x"]), int(p["y"])
        # A press-and-hold is a zero-distance swipe of the given duration.
        return f"input swipe {x} {y} {x} {y} {int(p.get('duration_ms', 600))}"
    if a.kind == "swipe":
        return (f"input swipe {int(p['x1'])} {int(p['y1'])} "
                f"{int(p['x2'])} {int(p['y2'])} {int(p.get('duration_ms', 300))}")
    if a.kind == "key":
        return f"input keyevent {_q(p['keycode'])}"
    if a.kind == "text":
        # `input text` treats %s as a space; quote for the shell layer.
        return f"input text {_q(str(p['s']).replace(' ', '%s'))}"
    if a.kind == "wait":
        return _sleep_line(int(p.get("ms", 0)) / 1000.0)
    raise ValueError(f"cannot compile action kind {a.kind!r}")


def actions_to_sh(actions: Iterable[Action], *, header: bool = True,
                  keep_timing: bool = True) -> str:
    """Compile actions into a runnable Android shell script.

    :param header: prepend shebang + a short comment banner.
    :param keep_timing: emit `sleep` gaps between actions from their `at_ms`
        offsets (as `Player` does). Set False for back-to-back execution.
    """
    actions = list(actions)
    lines: list[str] = []
    if header:
        lines += [
            SHEBANG,
            "# Generated by autoauto — replay on-device with: sh <this file>",
            f"# actions: {len(actions)}",
            "",
        ]
    prev_ms = 0
    for a in actions:
        if keep_timing:
            gap = (a.at_ms - prev_ms) / 1000.0
            if gap > 0:
                lines.append(_sleep_line(gap))
            prev_ms = a.at_ms
        lines.append(action_to_cmd(a))
    return "\n".join(lines) + "\n"


def save_sh(actions: Iterable[Action], path, **kwargs) -> None:
    from pathlib import Path
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(actions_to_sh(actions, **kwargs), encoding="utf-8", newline="\n")


def convert_recording(json_path, sh_path, **kwargs) -> None:
    """Read a saved JSON recording and write the equivalent `.sh` script."""
    save_sh(load_actions(json_path), sh_path, **kwargs)
